services:
  zookeeper:
    image: confluentinc/cp-zookeeper:lastest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_POST: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc//cp-kafka:lastest
    container_name: ms_fafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"