server:
  port: 8090
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hall-service
          uri: lb:http://HALL-SERVICE
          predicates:
            - Path=/api/v1/hall/**
          filter:
            - TokenRelay=
        - id: auditorium-service
          uri: lb:http://AUDITORIUM-SERVICE
          predicates:
            - Path=/api/v1/auditorium/**
          filter:
            - TokenRelay=
        - id: movie-service
          uri: lb:http://MOVIE-SERVICE
          predicates:
            - Path=/api/v1/movie/**
          filter:
            - TokenRelay=
        - id: screening-service
          uri: lb:http://SCREENING-SERVICE
          predicates:
            - Path=/api/v1/screening/**
          filter:
            - TokenRelay=
        - id: bookingticket-service
          uri: lb:http://BOOKINGTICKET-SERVICE
          predicates:
            - Path=/api/v1/ticket/**
          filter:
            - TokenRelay=
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
          filter:
            - TokenRelay=
        - id: front
          uri: http://localhost:4200
          predicates:
            - Path=/front/**
          filter:
            - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/whatamovie-front
        registration:
          keycloak:
            provider: keycloak
            client-id: client
            client-secret: soi3BsqvAuJohA6YoJIzjcjbjRhQHAtd
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/whatamovie-front/protocol/openid-connect/certs"
