server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: 123456
    hikari:
      schema: lighten_cinema
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/whatamovie-front/protocol/openid-connect/certs"