server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: 123456
    hikari:
      schema: lighten_cinema
  jpa:
    hibernate:
      ddl-auto: create
application:
  config:
    payment:
      zalo:
        appid: 2553
        key1: PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
        key2: Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3
        paymentEndpoint: https://sb-openapi.zalopay.vn/v2/create
        query_endpoint: https://sb-openapi.zalopay.vn/v2/query

