server:
  port: 8080
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8082
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
