eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: notification-service
  devtools:
    restart:
      enabled: false
  profiles:
    active: local
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
  batch:
    jdbc:
      initialize-schema: always
debug: true
logging:
  level:
    org.springframework.security: TRACE
