server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: iam-service
          uri: lb://IAM-SERVICE
          predicates:
            - Path=/iam/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
springdoc:
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: "iam-service"
        display-name: "IAM Service"
        url: /iam/v3/api-docs
      - name: "notification-service"
        display-name: "Notification Service"
        url: /notification/v3/api-docs
