server:
  port: 8086
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-super-snow-a1x5lauu-pooler.ap-southeast-1.aws.neon.tech/notification?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_GcU2yl7Cmpsb
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis-11769.c74.us-east-1-4.ec2.redns.redis-cloud.com
      port: 11769
  cache:
    type: redis
